# Generated by Django 5.1.4 on 2025-01-04 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_vendedores_producto_vendedor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vendedores',
            new_name='Vendedor',
        ),
        migrations.AlterField(
            model_name='producto',
            name='vendedor',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='productos.vendedor'),
        ),
    ]
