# Generated by Django 5.1.4 on 2025-01-04 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_rename_vendedores_vendedor_alter_producto_vendedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='vendedor',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='productos.vendedor'),
        ),
    ]
