# Generated by Django 5.1.4 on 2025-01-05 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_alter_producto_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='telefono',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
