# Generated by Django 5.1.4 on 2025-01-06 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_vendedor_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedor',
            name='telefono',
            field=models.IntegerField(blank=True, max_length=30, null=True),
        ),
    ]
