# Generated by Django 5.1.4 on 2025-01-06 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0011_alter_vendedor_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedor',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
