# Generated by Django 5.1.4 on 2025-01-12 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0016_envio_producto_envio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='envio',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.envio'),
        ),
    ]
