# Generated by Django 5.1.4 on 2025-01-12 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0017_alter_producto_envio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='envio',
        ),
    ]
