# Generated by Django 5.1.4 on 2025-01-12 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0018_remove_producto_envio'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='carritoproducto',
            unique_together={('carrito', 'producto')},
        ),
    ]
