# Generated by Django 5.1.4 on 2025-01-12 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0019_alter_carritoproducto_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='carritoproducto',
            unique_together=set(),
        ),
    ]
