# Generated by Django 5.1.4 on 2025-01-13 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0020_alter_carritoproducto_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='productos',
        ),
        migrations.AlterField(
            model_name='carritoproducto',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
