# Generated by Django 5.1.4 on 2025-02-06 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0024_pago_delete_diadisponible'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Localidad',
        ),
        migrations.AddField(
            model_name='barrio',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
