# Generated by Django 5.1.4 on 2025-02-06 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0025_delete_localidad_barrio_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
