# Generated by Django 5.1.4 on 2025-02-14 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0026_cupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tendencia',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
