# Generated by Django 5.1.4 on 2025-02-14 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0027_producto_tendencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True)),
            ],
        ),
    ]
