# Generated by Django 5.1.4 on 2025-02-14 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0028_descuento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='descuento',
            old_name='nombre',
            new_name='categoria',
        ),
    ]
