# Generated by Django 5.1.4 on 2025-02-14 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0029_rename_nombre_descuento_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descuento',
            name='porcentaje',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
