# Generated by Django 5.1.4 on 2025-02-19 02:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0034_alter_producto_fecha_publicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cantidad_vendida',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tendencia', models.BooleanField(blank=True, null=True)),
                ('cantidad_vendida', models.IntegerField(default=1)),
                ('fecha_venta', models.DateTimeField(default=django.utils.timezone.now)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.categoria')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='productos.producto')),
                ('talle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.talle')),
                ('usabilidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.usabilidad')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.vendedor')),
            ],
        ),
    ]
