# Generated by Django 5.1.4 on 2025-02-19 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0035_producto_cantidad_vendida_venta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
