# Generated by Django 5.1.4 on 2025-02-19 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0037_venta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('componente_reseñas', models.BooleanField(default=True)),
                ('componente_anuncios', models.BooleanField(default=True)),
                ('componente_tendencia', models.BooleanField(default=True)),
                ('componente_carrito_animado', models.BooleanField(default=True)),
                ('primario1', models.CharField(default='#485295', max_length=7)),
                ('primario2', models.CharField(default='#7cbcfc', max_length=7)),
                ('secundario1', models.CharField(default='#50c878', max_length=7)),
                ('secundario2', models.CharField(default='#2E8B57', max_length=7)),
                ('terciario', models.CharField(default='#333333', max_length=7)),
                ('cuarto', models.CharField(default='#85ee8562', max_length=7)),
            ],
        ),
    ]
