# Generated by Django 5.1.4 on 2025-02-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0038_configuracion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracion',
            name='cuarto',
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='primario1',
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='primario2',
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='secundario1',
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='secundario2',
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='terciario',
        ),
        migrations.AddField(
            model_name='configuracion',
            name='colores',
            field=models.JSONField(default=dict),
        ),
    ]
