# Generated by Django 5.1.4 on 2025-02-19 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0039_remove_configuracion_cuarto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colores', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Componentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('componente_reseñas', models.BooleanField(default=True)),
                ('componente_anuncios', models.BooleanField(default=True)),
                ('componente_tendencia', models.BooleanField(default=True)),
                ('componente_carrito_animado', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Configuracion',
        ),
    ]
