# Generated by Django 5.1.4 on 2025-02-19 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0040_colores_componentes_delete_configuracion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('codigo_hex', models.CharField(help_text='Código hexadecimal del color', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('cuarto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuarto', to='productos.color')),
                ('fondo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fondo', to='productos.color')),
                ('primario1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primario1', to='productos.color')),
                ('primario2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primario2', to='productos.color')),
                ('secundario1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secundario1', to='productos.color')),
                ('secundario2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secundario2', to='productos.color')),
                ('terciario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terciario', to='productos.color')),
            ],
        ),
        migrations.DeleteModel(
            name='Colores',
        ),
    ]
