# Generated by Django 5.1.4 on 2025-02-19 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0041_color_tema_delete_colores'),
    ]

    operations = [
        migrations.AddField(
            model_name='tema',
            name='activo',
            field=models.BooleanField(default=False),
        ),
    ]
