# Generated by Django 5.1.4 on 2025-02-20 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0042_tema_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tema',
            name='fondo',
        ),
        migrations.AddField(
            model_name='tema',
            name='fondo1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fondo1', to='productos.color'),
        ),
        migrations.AddField(
            model_name='tema',
            name='fondo2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fondo2', to='productos.color'),
        ),
        migrations.AddField(
            model_name='tema',
            name='fondo3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fondo3', to='productos.color'),
        ),
        migrations.AddField(
            model_name='tema',
            name='fondo4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fondo4', to='productos.color'),
        ),
        migrations.AddField(
            model_name='tema',
            name='fondo5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fondo5', to='productos.color'),
        ),
    ]
