# Generated by Django 5.1.4 on 2025-02-20 18:25

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0043_remove_tema_fondo_tema_fondo1_tema_fondo2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContenidosWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('contenido', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='contenidoWeb/')),
            ],
        ),
    ]
