# Generated by Django 5.1.4 on 2025-02-21 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0044_contenidosweb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='codigo_hex',
            field=models.CharField(help_text='Código hexadecimal del color', max_length=15),
        ),
    ]
