# Generated by Django 5.1.4 on 2025-02-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0046_remove_venta_cantidad_remove_venta_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='precio_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
