# Generated by Django 5.1.4 on 2025-02-22 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0047_venta_precio_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fuente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('activa', models.BooleanField(default=False)),
            ],
        ),
    ]
