# Generated by Django 5.1.4 on 2025-02-22 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0048_fuente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fuente',
            old_name='nombre',
            new_name='fuentePrimaria',
        ),
    ]
