# Generated by Django 5.1.4 on 2025-02-22 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0049_rename_nombre_fuente_fuenteprimaria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fuente',
            old_name='activa',
            new_name='activo',
        ),
    ]
