# Generated by Django 5.1.4 on 2025-02-25 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0050_rename_activa_fuente_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuntosClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=False)),
            ],
        ),
    ]
