# Generated by Django 5.1.4 on 2025-02-25 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0052_puntosclubporusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='puntos_club',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
