# Generated by Django 5.1.4 on 2025-02-25 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0053_producto_puntos_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='puntos_club_acumulados',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
