# Generated by Django 5.1.4 on 2025-02-26 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0054_venta_puntos_club_acumulados'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cupon',
            old_name='nombre',
            new_name='codigo',
        ),
        migrations.AddField(
            model_name='cupon',
            name='fecha_expiracion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
