# Generated by Django 5.1.4 on 2025-02-26 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0055_rename_nombre_cupon_codigo_cupon_fecha_expiracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntosclubporusuario',
            name='cantidad_puntos',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
