# Generated by Django 5.1.4 on 2025-02-26 21:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0057_customuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PuntosClubPorUsuario',
            new_name='PerfilUsuario',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
