# Generated by Django 5.1.4 on 2025-02-26 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0058_rename_puntosclubporusuario_perfilusuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='cantidad_puntos',
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='puntos_acumulados',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
