# Generated by Django 5.1.4 on 2025-02-26 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0059_remove_perfilusuario_cantidad_puntos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialPuntos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos_obtenidos', models.IntegerField()),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='productos.perfilusuario')),
            ],
        ),
    ]
