# Generated by Django 5.1.4 on 2025-02-28 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0060_historialpuntos'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='id_venta',
            field=models.CharField(default=0, max_length=7),
        ),
    ]
