# Generated by Django 5.1.4 on 2025-02-28 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0061_venta_id_venta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='id',
        ),
        migrations.AlterField(
            model_name='venta',
            name='id_venta',
            field=models.CharField(max_length=7, primary_key=True, serialize=False),
        ),
    ]
