# Generated by Django 5.1.4 on 2025-03-01 02:23

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0062_remove_venta_id_alter_venta_id_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='qr_codes/'),
        ),
    ]
