# Generated by Django 5.1.4 on 2025-03-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0063_producto_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='valor_en_puntos',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
