# Generated by Django 5.1.4 on 2025-03-02 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0064_producto_valor_en_puntos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleventa',
            name='venta',
        ),
    ]
