# Generated by Django 5.1.4 on 2025-03-02 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0065_remove_detalleventa_venta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='id_venta',
        ),
        migrations.AddField(
            model_name='venta',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
