# Generated by Django 5.1.4 on 2025-03-02 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0066_remove_venta_id_venta_venta_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
