# Generated by Django 5.1.4 on 2025-03-03 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0069_venta_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='comprador_sin_cuenta',
            field=models.CharField(blank=True, default='---', max_length=100, null=True),
        ),
    ]
