# Generated by Django 5.1.4 on 2025-03-04 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0070_venta_comprador_sin_cuenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='barrio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.barrio'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='dni',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='domicilio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
