# Generated by Django 5.1.4 on 2025-03-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0071_perfilusuario_barrio_perfilusuario_dni_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='nombre_apellido',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
