# Generated by Django 5.1.4 on 2025-03-04 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0072_perfilusuario_nombre_apellido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='vendedor',
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='nombre_apellido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
