# Generated by Django 5.1.4 on 2025-03-04 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0073_remove_producto_vendedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descuento',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descuentos', to='productos.categoria'),
        ),
    ]
