# Generated by Django 5.1.4 on 2025-03-06 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0075_vendedor_barrio_vendedor_dni_vendedor_domicilio_and_more'),
    ]

    operations = [
       
        migrations.CreateModel(
            name='ProductoFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(default=0)),
                ('cantidad_vendida', models.IntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talles', to='productos.producto')),
                ('talle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.talle')),
            ],
            options={
                'unique_together': {('producto', 'talle')},
            },
        ),
        migrations.AddField(
            model_name='carritoproducto',
            name='producto_final',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.productofinal'),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='producto_final',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.productofinal'),
        ),
    ]
