# Generated by Django 5.1.4 on 2025-03-06 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0076_remove_carritoproducto_producto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carritoproducto',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='cantidad_vendida',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='talle',
        ),
        migrations.AlterField(
            model_name='talle',
            name='nombre',
            field=models.CharField(max_length=10),
        ),
    ]
