# Generated by Django 5.1.4 on 2025-03-06 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0077_remove_carritoproducto_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carritoproducto',
            name='producto_final',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.productofinal'),
        ),
    ]
