# Generated by Django 5.1.4 on 2025-03-07 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0078_alter_carritoproducto_producto_final'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleventa',
            name='producto',
        ),
    ]
