# Generated by Django 5.1.4 on 2025-03-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0080_alter_perfilusuario_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talle',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
