# Generated by Django 5.1.4 on 2025-03-10 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0081_alter_talle_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentes',
            name='componente_sonido',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='contenidosweb',
            name='contenido',
            field=models.TextField(blank=True, null=True),
        ),
    ]
