# Generated by Django 5.1.4 on 2025-03-11 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0082_componentes_componente_sonido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentes',
            name='componente_categoria',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='componentes',
            name='componente_usabilidad_estado',
            field=models.BooleanField(default=True),
        ),
    ]
