# Generated by Django 5.1.4 on 2025-03-15 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0085_estadosventa_venta_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenidosweb',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
