# Generated by Django 5.1.4 on 2025-03-15 01:00

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0086_alter_contenidosweb_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='categorias/'),
        ),
    ]
