# Generated by Django 5.1.4 on 2025-03-15 01:46

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0087_categoria_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformacionWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('contenido', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='contenidoWeb/')),
            ],
        ),
    ]
