# Generated by Django 5.1.4 on 2025-03-17 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0088_informacionweb'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Componentes',
            new_name='Componentes_Configraciones',
        ),
    ]
