# Generated by Django 5.1.4 on 2025-03-17 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0089_rename_componentes_componentes_configraciones'),
    ]

    operations = [
        migrations.RenameField(
            model_name='componentes_configraciones',
            old_name='componente_usabilidad_estado',
            new_name='componente_canjes',
        ),
        migrations.AddField(
            model_name='componentes_configraciones',
            name='componente_probarProducto',
            field=models.BooleanField(default=True),
        ),
    ]
