# Generated by Django 5.1.4 on 2025-03-17 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0090_rename_componente_usabilidad_estado_componentes_configraciones_componente_canjes_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Componentes_Configraciones',
            new_name='Componentes_Configuraciones',
        ),
    ]
