# Generated by Django 5.1.4 on 2025-03-17 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0091_rename_componentes_configraciones_componentes_configuraciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentes_configuraciones',
            name='componente_varios',
            field=models.BooleanField(default=True),
        ),
    ]
