# Generated by Django 5.1.4 on 2025-03-18 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0093_roles_vendedor_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diseños',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
    ]
