# Generated by Django 5.1.4 on 2025-03-18 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0094_diseños'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedor',
            name='rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.roles'),
        ),
    ]
