# Generated by Django 5.1.4 on 2025-03-20 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0095_alter_vendedor_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='tema',
            name='colorFuente1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colorFuente1', to='productos.color'),
        ),
    ]
