# Generated by Django 5.1.4 on 2025-03-21 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0098_remove_tema_colorfuente_tema_colorfuente1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuente',
            name='fuenteSecundaria',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
