# Generated by Django 5.1.4 on 2025-03-21 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0099_fuente_fuentesecundaria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tema',
            name='colorFuente1',
        ),
        migrations.RemoveField(
            model_name='tema',
            name='colorFuente2',
        ),
        migrations.AddField(
            model_name='tema',
            name='colorFuente1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colorFuente1', to='productos.color'),
        ),
        migrations.AddField(
            model_name='tema',
            name='colorFuente2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colorFuente2', to='productos.color'),
        ),
    ]
