# Generated by Django 5.1.4 on 2025-03-22 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0100_remove_tema_colorfuente11_remove_tema_colorfuente12_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseños',
            name='activo',
            field=models.BooleanField(default=False),
        ),
    ]
