# Generated by Django 5.1.4 on 2025-03-23 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0101_diseños_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuente',
            name='fuentePrimaria',
        ),
        migrations.RemoveField(
            model_name='fuente',
            name='fuenteSecundaria',
        ),
        migrations.RemoveField(
            model_name='tema',
            name='colorFuente1',
        ),
        migrations.RemoveField(
            model_name='tema',
            name='colorFuente2',
        ),
        migrations.AddField(
            model_name='fuente',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='FuenteAplicar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_fuente', models.CharField(choices=[('primaria', 'Primaria'), ('secundaria', 'Secundaria'), ('terciaria', 'Terciaria')], max_length=20)),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.color')),
                ('fuente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.fuente')),
            ],
        ),
        migrations.AddField(
            model_name='tema',
            name='fuente_primaria',
            field=models.ForeignKey(limit_choices_to={'tipo_fuente': 'primaria'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuente_primaria', to='productos.fuenteaplicar'),
        ),
        migrations.AddField(
            model_name='tema',
            name='fuente_secundaria',
            field=models.ForeignKey(limit_choices_to={'tipo_fuente': 'secundaria'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuente_secundaria', to='productos.fuenteaplicar'),
        ),
        migrations.AddField(
            model_name='tema',
            name='fuente_terciaria',
            field=models.ForeignKey(limit_choices_to={'tipo_fuente': 'terciaria'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuente_terciaria', to='productos.fuenteaplicar'),
        ),
    ]
