# Generated by Django 5.1.4 on 2025-03-23 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0102_remove_fuente_fuenteprimaria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuenteaplicar',
            name='tipo_fuente',
        ),
        migrations.AlterField(
            model_name='tema',
            name='fuente_primaria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuente_primaria', to='productos.fuenteaplicar'),
        ),
        migrations.AlterField(
            model_name='tema',
            name='fuente_secundaria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuente_secundaria', to='productos.fuenteaplicar'),
        ),
        migrations.AlterField(
            model_name='tema',
            name='fuente_terciaria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuente_terciaria', to='productos.fuenteaplicar'),
        ),
    ]
