# Generated by Django 5.1.4 on 2025-03-23 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0103_remove_fuenteaplicar_tipo_fuente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tema',
            name='fuente_primaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temas_primaria', to='productos.fuenteaplicar'),
        ),
        migrations.AlterField(
            model_name='tema',
            name='fuente_secundaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temas_secundaria', to='productos.fuenteaplicar'),
        ),
        migrations.AlterField(
            model_name='tema',
            name='fuente_terciaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temas_terciaria', to='productos.fuenteaplicar'),
        ),
    ]
