# Generated by Django 5.1.4 on 2025-03-24 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0104_alter_tema_fuente_primaria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=50)),
                ('moneda', models.CharField(max_length=50)),
                ('impuesto', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
