# Generated by Django 5.1.4 on 2025-03-26 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0105_impuesto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Impuesto',
        ),
    ]
