# Generated by Django 5.1.4 on 2025-04-02 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0106_delete_impuesto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='usabilidad',
        ),
        migrations.DeleteModel(
            name='Usabilidad',
        ),
    ]
