# Generated by Django 5.1.4 on 2025-04-02 02:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0107_remove_producto_usabilidad_delete_usabilidad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vendedor',
            new_name='SuperUsuario',
        ),
    ]
