# Generated by Django 5.1.4 on 2025-04-02 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0108_rename_vendedor_superusuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='puntos_club',
            new_name='puntos_club_acumulables',
        ),
    ]
