# Generated by Django 5.1.4 on 2025-04-02 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0109_rename_puntos_club_producto_puntos_club_acumulables'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pago',
        ),
        migrations.AlterField(
            model_name='venta',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.superusuario'),
        ),
        migrations.DeleteModel(
            name='PasswordResetCode',
        ),
    ]
