# Generated by Django 5.1.4 on 2025-04-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0111_pago_passwordresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='comprobante_pdf',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes/'),
        ),
    ]
