# Generated by Django 5.1.4 on 2025-04-08 23:34

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0112_venta_comprobante_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='comprobante_pdf',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='comprobantes/'),
        ),
    ]
