# Generated by Django 5.1.4 on 2025-04-09 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0113_alter_venta_comprobante_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='pais',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
