# Generated by Django 5.1.4 on 2025-04-11 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0114_perfilusuario_pais'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='favoritos',
            field=models.ManyToManyField(blank=True, related_name='favoritos_de_usuarios', to='productos.productofinal'),
        ),
    ]
