# Generated by Django 5.1.4 on 2025-04-16 23:40

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0115_perfilusuario_favoritos'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='imagen',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='usuarios/'),
        ),
        migrations.AddField(
            model_name='superusuario',
            name='imagen',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='usuarios/'),
        ),
    ]
