# Generated by Django 5.1.4 on 2025-04-17 00:38

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0116_perfilusuario_imagen_superusuario_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen_secundaria',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='productos/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_terciaria',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='productos/'),
        ),
    ]
