# Generated by Django 5.1.4 on 2025-04-18 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0117_producto_imagen_secundaria_producto_imagen_terciaria'),
    ]



    operations = [
    
     #   migrations.CreateModel(
      #  name='Marca',
       # fields=[
        #    ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
         #   ('nombre', models.CharField(max_length=100, unique=True)),
        #],
    #),
    #migrations.AddField(
     #   model_name='producto',
      #  name='marca',
       # field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='productos.marca'),
    #),
    migrations.CreateModel(
        name='Atributo',
        fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ('nombre', models.CharField(max_length=50)),
            ('valor', models.CharField(max_length=100)),
        ],
    ),
        migrations.RemoveField(
            model_name='productofinal',
            name='producto',
        ),
       # migrations.RemoveField(
        #    model_name='productofinal',
         #   name='talle',
        #),
        migrations.RemoveField(
            model_name='carritoproducto',
            name='producto_final',
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='producto_final',
        ),
        migrations.AddField(
            model_name='producto',
            name='atributos',
            field=models.ManyToManyField(blank=True, related_name='productos', to='productos.atributo'),
        ),
       
        migrations.CreateModel(
            name='Variante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(default=0)),
                ('cantidad_vendida', models.IntegerField(default=0)),
                ('sku', models.CharField(blank=True, max_length=100, null=True)),
                ('atributos', models.ManyToManyField(related_name='variantes', to='productos.atributo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='productos.producto')),
            ],
          
        ),
        migrations.AddField(
            model_name='carritoproducto',
            name='variante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.variante'),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='variante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.variante'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='favoritos',
            field=models.ManyToManyField(blank=True, related_name='favoritos_de_usuarios', to='productos.variante'),
        ),
        #migrations.DeleteModel(
         #   name='Talle',
        #),
        #migrations.DeleteModel(
         #   name='ProductoFinal',
        #),
    ]
