# Generated by Django 5.1.4 on 2025-04-18 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0118_atributo_marca_alter_productofinal_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='variante',
            unique_together=set(),
        ),
    ]
