# Generated by Django 5.1.4 on 2025-04-19 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0119_alter_variante_unique_together'),
    ]

    operations = [

    ]
