# Generated by Django 5.1.4 on 2025-04-19 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0120_marca_producto_marca_delete_productofinal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='favoritos',
            field=models.ManyToManyField(null=True, related_name='favoritos_de_usuarios', to='productos.variante'),
        ),
    ]
