# Generated by Django 5.1.4 on 2025-04-19 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0121_alter_perfilusuario_favoritos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carritoproducto',
            name='variante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.variante'),
        ),
    ]
