# Generated by Django 5.1.4 on 2025-04-19 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0122_alter_carritoproducto_variante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='favoritos',
            field=models.ManyToManyField(blank=True, related_name='favoritos_de_usuarios', to='productos.variante'),
        ),
    ]
