# Generated by Django 5.1.4 on 2025-04-19 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0123_alter_perfilusuario_favoritos'),
    ]

    operations = [
        
    ]
