# Generated by Django 5.1.4 on 2025-04-19 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0128_marca_producto_marca_delete_productofinal_and_more'),
    ]

    operations = [
        # Eliminar el índice obsoleto
        migrations.RunSQL(
            sql="""
            DROP INDEX IF EXISTS productos_perfilusuario_favoritos_productofinal_id_c35f0864;
            """,
            reverse_sql="""
            CREATE INDEX productos_perfilusuario_favoritos_productofinal_id_c35f0864 ON productos_perfilusuario_favoritos (variante_id);
            """
        ),
    ]