# Generated by Django 5.1.4 on 2025-04-20 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0131_marca_producto_marca_delete_productofinal_and_more'),
    ]

    operations = [
        
    ]
