# Generated by Django 5.1.4 on 2025-04-20 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0132_marca_producto_marca_delete_productofinal_and_more'),
    ]

   
