# Generated by Django 5.1.4 on 2025-04-20 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0133_marca_producto_marca_delete_productofinal_and_more'),
    ]

    operations = [
    ]
