# Generated by Django 5.1.4 on 2025-04-20 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0134_auto_20250419_2152'),
    ]
    operations = [
        # Eliminar la clave foránea de producto_final_id
        migrations.RunSQL(
            sql="""
            ALTER TABLE productos_detalleventa
            DROP CONSTRAINT IF EXISTS productos_detalleven_producto_final_id_45c2933f_fk_productos;
            """,
            reverse_sql="""
            ALTER TABLE productos_detalleventa
            ADD CONSTRAINT productos_detalleven_producto_final_id_45c2933f_fk_productos
            FOREIGN KEY (producto_final_id) REFERENCES productos_productofinal(id) DEFERRABLE INITIALLY DEFERRED;
            """
        ),
        # Eliminar la clave foránea de producto_talle_id
        migrations.RunSQL(
            sql="""
            ALTER TABLE productos_detalleventa
            DROP CONSTRAINT IF EXISTS productos_detalleven_producto_talle_id_d63975a2_fk_productos;
            """,
            reverse_sql="""
            ALTER TABLE productos_detalleventa
            ADD CONSTRAINT productos_detalleven_producto_talle_id_d63975a2_fk_productos
            FOREIGN KEY (producto_talle_id) REFERENCES productos_productotalle(id) DEFERRABLE INITIALLY DEFERRED;
            """
        ),
        # Renombrar producto_final_id a variante_id
        migrations.RunSQL(
            sql="""
            ALTER TABLE productos_detalleventa
            RENAME COLUMN producto_final_id TO variante_id;
            """,
            reverse_sql="""
            ALTER TABLE productos_detalleventa
            RENAME COLUMN variante_id TO producto_final_id;
            """
        ),
        # Eliminar producto_talle_id
        migrations.RunSQL(
            sql="""
            ALTER TABLE productos_detalleventa
            DROP COLUMN IF EXISTS producto_talle_id;
            """,
            reverse_sql="""
            ALTER TABLE productos_detalleventa
            ADD COLUMN producto_talle_id BIGINT;
            """
        ),
        # Agregar la nueva clave foránea para variante_id
        migrations.RunSQL(
            sql="""
            ALTER TABLE productos_detalleventa
            ADD CONSTRAINT productos_detalleventa_variante_id_fk
            FOREIGN KEY (variante_id) REFERENCES productos_variante(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
            """,
            reverse_sql="""
            ALTER TABLE productos_detalleventa
            DROP CONSTRAINT IF EXISTS productos_detalleventa_variante_id_fk;
            """
        ),
    ]
