# Generated by Django 5.1.4 on 2025-04-21 03:00

import django.db.models.deletion
import storages.backends.s3
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0135_auto_20250419_2152'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAtributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
       
        migrations.RemoveField(
            model_name='variante',
            name='atributos',
        ),
        migrations.RemoveField(
            model_name='variante',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='variante',
        ),
        migrations.RemoveField(
            model_name='carritoproducto',
            name='variante',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='favoritos',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='atributos',
            new_name='atributos_valores',
        ),
        migrations.AddField(
            model_name='carritoproducto',
            name='combinacion',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='carritoproducto',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.producto'),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='combinacion',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.producto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='combinaciones',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='producto',
            name='modelo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='tiene_variantes',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='dni',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='domicilio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='imagen',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='perfiles/'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='nombre_apellido',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='pais',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='puntos_acumulados',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='productos.categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descuento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tendencia',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combinacion', models.JSONField(default=list)),
                ('perfil_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.perfilusuario')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
        ),
       
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['categoria'], name='productos_p_categor_17b5fc_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['tendencia'], name='productos_p_tendenc_326c8f_idx'),
        ),
        migrations.AddIndex(
            model_name='tipoatributo',
            index=models.Index(fields=['nombre'], name='productos_t_nombre_32b9ad_idx'),
        ),
        migrations.AddField(
            model_name='atributo',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='productos.tipoatributo'),
        ),
        migrations.AlterUniqueTogether(
            name='atributo',
            unique_together={('tipo', 'valor')},
        ),
        migrations.AddIndex(
            model_name='atributo',
            index=models.Index(fields=['tipo', 'valor'], name='productos_a_tipo_id_798315_idx'),
        ),
     
       
        migrations.AlterUniqueTogether(
            name='favorito',
            unique_together={('perfil_usuario', 'producto', 'combinacion')},
        ),
        migrations.RemoveField(
            model_name='atributo',
            name='nombre',
        ),
    ]
