# Generated by Django 5.1.4 on 2025-04-21 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0136_tipoatributo_alter_productofinal_unique_together_and_more'),
    ]

    operations = [
       
    ]
