# Generated by Django 5.1.4 on 2025-04-21 20:19

import django.db.models.deletion
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0137_marca_alter_productofinal_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CombinacionProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=255)),
                ('atributos', models.JSONField(default=list)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('cantidad_vendida', models.PositiveIntegerField(default=0)),
                ('sku', models.CharField(blank=True, max_length=100)),
                ('precio_especifico', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='combinaciones/')),
            ],
        ),
        
        migrations.RemoveField(
            model_name='producto',
            name='combinaciones',
        ),
        migrations.AlterField(
            model_name='atributo',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='productos.tipoatributo'),
        ),
        migrations.AddField(
            model_name='combinacionproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combinaciones_detalle', to='productos.producto'),
        ),
       
       
        migrations.AddIndex(
            model_name='combinacionproducto',
            index=models.Index(fields=['producto', 'clave'], name='productos_c_product_b6f929_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='combinacionproducto',
            unique_together={('producto', 'clave')},
        ),
    ]
