# Generated by Django 5.1.4 on 2025-04-21 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0138_combinacionproducto_marca_and_more'),
    ]

    operations = [
      
    ]
