# Generated by Django 5.1.4 on 2025-04-21 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0139_marca_alter_productofinal_unique_together_and_more'),
    ]

    operations = [
       
        migrations.RemoveField(
            model_name='combinacionproducto',
            name='precio_especifico',
        ),
       
    ]
