# Generated by Django 5.1.4 on 2025-04-21 23:12

import django.db.models.deletion
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0140_marca_alter_productofinal_unique_together_and_more'),
    ]

    operations = [
      
        migrations.CreateModel(
            name='ProductoAtributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('cantidad_vendida', models.PositiveIntegerField(default=0)),
                ('imagen', models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='atributos/')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='modelo_talle',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='combinacionproducto',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='combinacionproducto',
            name='producto',
        ),
      
      migrations.AddField(
            model_name='atributo',
            name='nombre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Variante',
        ),
        migrations.RemoveIndex(
            model_name='atributo',
            name='productos_a_tipo_id_798315_idx',
        ),
        migrations.RemoveIndex(
            model_name='producto',
            name='productos_p_categor_17b5fc_idx',
        ),
        migrations.RemoveIndex(
            model_name='producto',
            name='productos_p_tendenc_326c8f_idx',
        ),
        migrations.AlterUniqueTogether(
            name='atributo',
            unique_together={('nombre', 'valor')},
        ),
        migrations.AlterUniqueTogether(
            name='producto',
            unique_together={('nombre', 'modelo_talle')},
        ),
        
        
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='productos.categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tendencia',
            field=models.BooleanField(blank=True, null=True),
        ),
     
        
    
        migrations.AddField(
            model_name='productoatributo',
            name='atributo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_atributos', to='productos.atributo'),
        ),
        migrations.AddField(
            model_name='productoatributo',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_atributos', to='productos.producto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='atributos',
            field=models.ManyToManyField(related_name='productos', through='productos.ProductoAtributo', to='productos.atributo'),
        ),
        migrations.AddIndex(
            model_name='tipoproducto',
            index=models.Index(fields=['nombre'], name='productos_t_nombre_bcb11f_idx'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='productos.tipoproducto'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['nombre', 'modelo_talle'], name='productos_p_nombre_0df4cd_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['tipo'], name='productos_p_tipo_id_67516a_idx'),
        ),
      
        migrations.DeleteModel(
            name='CombinacionProducto',
        ),
       
        migrations.RemoveField(
            model_name='atributo',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='atributos_valores',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='tiene_variantes',
        ),
        migrations.AddIndex(
            model_name='productoatributo',
            index=models.Index(fields=['producto', 'atributo'], name='productos_p_product_58b8c7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productoatributo',
            unique_together={('producto', 'atributo')},
        ),
        migrations.DeleteModel(
            name='TipoAtributo',
        ),
    ]
