# Generated by Django 5.1.4 on 2025-04-23 04:03

import django.db.models.deletion
import storages.backends.s3
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0141_marca_productoatributo_tipoproducto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
      
        migrations.AlterUniqueTogether(
            name='favorito',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='favorito',
            name='perfil_usuario',
        ),
        migrations.RemoveField(
            model_name='favorito',
            name='producto',
        ),
      
        migrations.AddField(
            model_name='perfilusuario',
            name='favoritos',
            field=models.ManyToManyField(blank=True, related_name='favoritos_de_usuarios', to='productos.productoatributo'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='dni',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='domicilio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='imagen',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='usuarios/'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='nombre_apellido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='pais',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='puntos_acumulados',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='atributo',
            index=models.Index(fields=['nombre', 'valor'], name='productos_a_nombre_3f7821_idx'),
        ),
       
    
        migrations.DeleteModel(
            name='Favorito',
        ),
        
    ]
