# Generated by Django 5.1.4 on 2025-04-23 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0142_marca_alter_favorito_unique_together_and_more'),
    ]

    operations = [
       
       
        migrations.AddField(
            model_name='carritoproducto',
            name='producto_atributo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.productoatributo'),
        ),
         migrations.AlterUniqueTogether(
            name='carritoproducto',
            unique_together={('carrito', 'producto_atributo')},
        ),
        migrations.AlterField(
            model_name='carritoproducto',
            name='carrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='productos.carrito'),
        ),
        
       
        migrations.RemoveField(
            model_name='carritoproducto',
            name='combinacion',
        ),
        migrations.RemoveField(
            model_name='carritoproducto',
            name='producto',
        ),
    ]
