# Generated by Django 5.1.4 on 2025-04-23 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0143_alter_productofinal_unique_together_and_more'),
    ]

    operations = [
        
       
      
    ]
